# Generated by Django 3.1.5 on 2021-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20210127_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_path_2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_path_3',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_path_4',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.TextField(default=None),
        ),
    ]
