# Generated by Django 3.1.5 on 2021-01-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20210130_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='product_id',
            new_name='product',
        ),
    ]
