# Generated by Django 3.1.5 on 2021-01-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20210130_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
