# Generated by Django 3.1.5 on 2021-02-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_no',
        ),
    ]
