# Generated by Django 3.1.5 on 2021-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20210202_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review',
            name='color',
            field=models.CharField(default='red', max_length=255),
            preserve_default=False,
        ),
    ]
