# Generated by Django 3.1.5 on 2021-02-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_customer_review_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carousel',
            field=models.BooleanField(default=0),
        ),
    ]
