# Generated by Django 3.1.5 on 2021-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_product_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default=402301),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street2',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
    ]
