# Generated by Django 3.1.5 on 2021-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20210205_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='first',
            field=models.CharField(default='na', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last',
            field=models.CharField(default='na', max_length=255),
            preserve_default=False,
        ),
    ]
