# Generated by Django 3.1.5 on 2021-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_auto_20210205_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.FloatField(default=2500),
            preserve_default=False,
        ),
    ]
