# Generated by Django 3.1.5 on 2021-02-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_product_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_desc',
            field=models.CharField(default='LIT Lamp', max_length=255),
            preserve_default=False,
        ),
    ]
